apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio
spec:
  releaseName: istio-operator
  chart:
    spec:
      chart: manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio
  name: istio-default
spec:
  profile: demo
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"