apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
spec:
  releaseName: istio-operator
  chart:
    git: git@github.com:istio/istio
    ref: master
    path: manifests/charts/istio-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values: